server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI5t9qSVPveWdfebsogcEK
    keySecret: 35SGvQoAhiObbZBhmgf0d2ZDV1asOq
    bucketName: srb-lzg